name: Handle Source Notification

on:
  repository_dispatch:
    types: [source_repo_updated]

jobs:
  process-change:
    runs-on: ubuntu-latest
    steps:
      - name: Install cve-cli
        run: |
          npm install cve-cli-0.0.2-rc2.tgz

      - name: Run cve-cli
        run: |
          pwd
          ls -al
          NODE_CONFIG_ENV=devel ./bin/run.js date -v
          NODE_CONFIG_ENV=devel ./bin/run.js delta deltalog get

      - name: Log Payload
        run: |
          echo "Received update from source!"
          echo "Commit SHA: ${{ github.event.client_payload.sha }}"
          echo "Message: ${{ github.event.client_payload.message }}"
