name: Handle Source Notification

on:
  repository_dispatch:
    types: [source_repo_updated]
  workflow_dispatch:
    inputs:
      params:
        description: 'command line arguments'
        required: false
        default: ''

jobs:
  process-change:
    runs-on: ubuntu-latest
    steps:
      - name: Install cve-cli
        run: |
          # npm install cve-cli-0.0.2-rc2.tgz
          pwd
          tar -xzvf cve-cli-0.0.2-rc2.tgz
          cd package
          npm install
          
      - name: Run cve-cli
        run: |
          pwd
          ls -al
          NODE_CONFIG_ENV=devel ./bin/run.js date -v
          NODE_CONFIG_ENV=devel ./bin/run.js delta deltalog get

      - name: Log Payload
        run: |
          echo "Received update from source!"
          echo "Commit SHA: ${{ github.event.client_payload.sha }}"
          echo "Message: ${{ github.event.client_payload.message }}"
